name: Build CLEOAddon
on: push
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup premake
        uses: abel0b/setup-premake@v2
        with:
          version: "5.0.0-beta1"
      - name: Configure build
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.platform}} 
      - name: Build plugin
        run: |
          cd tools
          premake5 vs2022
          cd ../build
          MsBuild CLEOAddon.sln /property:Configuration=Release /p:Platform=${{matrix.platform}} /t:CLEOAddon
      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: CLEOAddon
          path: build\bin\CLEOAddon.cleo
      - name: Archive plugin
        uses: papeloto/action-zip@v1
        with:
          files: build\bin\CLEOAddon.cleo
          dest: CLEOAddon${{matrix.platform}}.zip
      - name: Add build to release tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: CLEOAddon${{matrix.platform}}.zip
          name: "CLEOAddon ${{matrix.platform}}"
          body: "CLEOAddon for ${{matrix.platform}}. This release is updated regularly"
          allowUpdates: true
          tag: "${{matrix.platform}}-latest"
        
